server:
  port: 50003

spring:
  datasource:
    url: jdbc:oracle:thin:@//172.17.110.122:1521/essp
    username: system
    password: manager
    hikari:
      minimumIdle: 5
      maximumPoolSize: 1000
      idleTimeout: 30000
      maxLifetime: 2000000
      connectionTimeout: 30000
      pool-name: UsciHikariPool
      leak-detection-threshold: 30000

eureka:
  client:
    region: default
    registryFetchIntervalSeconds: 5
    enabled: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:58761/eureka}
  instance:
    preferIpAddress: true